### ISSUE TITLE
Next-app example gets stuck at loading after clicking on login

### ISSUE THREAD

**Issue by realisticattorney** [Web3Auth/Web3Auth#101]
I've just downloaded the latest source code, got into the next-app folder, install dependencies with yarn then run yarn dev. I've left my metamask wallet on the mainnet just in case. Not working

![image](https://user-images.githubusercontent.com/66647706/160292533-ea750a87-d8b1-428e-b105-1bfc425ae9c9.png)

**Comment by Liuminjin** [comment]
You will need to synchronize your wallet and then you debug it

**Comment by realisticattorney** [comment]
> You will need to synchronize your wallet and then you debug it

Thanks for the response. Synchronize how? In metamask settings, I have sync with mobile (I'm on a PC) and then an experimental that's not related to this bug. I'm connected to the mainnet and my other apps are working just fine.

**Comment by himanshuchawla009** [comment]
@tainguyentt can you check this.

**Comment by tainguyentt** [comment]
Hi @realisticattorney, I pulled latest code of next-app and it ran successfully. Could you help to list out steps so that I can follow to reproduce this issue?

**Comment by chaitanyapotti** [comment]
This is fixed now
