### ISSUE TITLE
Authentication with OpenloginAdapter does not persist across browser tabs

### ISSUE THREAD

**Issue by pmualaba** [Web3Auth/Web3Auth#119]
When you login using the popup OpenloginAdapter (be it social login or metamask login) you only remain authenticated as long as you stay inside 1 browser tab. If your application contains target _blank links (within the same domain) you are logged out and you need to login again for that browser tab.

Desired behaviour: 
Persist authentication across browser tabs if the application domain is the same.

setup :

` const adapter = new OpenloginAdapter({
          adapterSettings: {
            network: process.env['NEXT_PUBLIC_BLOCKCHAIN_NETWORK'] === 'mainnet' ? 'mainnet' : 'testnet',
            clientId,
            uxMode: 'popup',
          },
        });`

**Comment by himanshuchawla009** [comment]
Hi, Plz mention browser and os details.

**Comment by bonnusi** [comment]
Hi, for metamask the same problem

**Comment by bonnusi** [comment]
Hi, for "uxMode: 'redirect'", i have the same problem

**Comment by bonnusi** [comment]
@himanshuchawla009 @chaitanyapotti still not working for me, last version when work "@web3auth/web3auth": "^0.5.1", can your help me, please?

**Comment by chaitanyapotti** [comment]
Did you use a new parameter storage: local.?

**Comment by bonnusi** [comment]
@chaitanyapotti Oh thanks, I thought was the default "local", i forget check this
