### ISSUE TITLE
Unable to detect device share error page

### ISSUE THREAD

**Issue by zachdorcinville21** [Web3Auth/Web3Auth#1238]
### **Describe the bug**

This error page is sometimes shown during the authentication process:
![telegram-cloud-photo-size-1-5039582087186852693-y](https://user-images.githubusercontent.com/16417769/212998801-83893358-9a9c-4d99-b173-e44b2e97d103.jpg)

### **To Reproduce**

It does not occur on each log in/ sign up, but when it does, this is how to reproduce:

1. Call the `authenticateUser()` method from the `Web3AuthCore` class
2. Sign in with SSO
3. Before the redirect back to the origin, the above error will sometimes show.

### **Expected behavior**

After authenticating, the user should be redirected seamlessly back to the origin.

### **Device Info (please complete the following information):**

- Device: Macbook, iPhone, Android (seems to be device agnostic)
- OS: MacOS, iOS, Windows
- Browser: Chrome
- Version: 109.0.5414.87
- Web3Auth Versions: `"@web3auth/base": "^4.0.0-alpha.0",
    "@web3auth/core": "^4.0.0-alpha.0",
    "@web3auth/metamask-adapter": "^4.0.0-alpha.0",
    "@web3auth/openlogin-adapter": "^4.0.0-alpha.0",
    "@web3auth/web3auth": "^2.1.3",`

### **Additional context**

This error screen only shows some of the time.

**Comment by himanshuchawla009** [comment]
please capture and attach the screenshot of console logs when this error happens, that would be helpful for us in debugging.  @zachdorcinville21

**Comment by chaitanyapotti** [comment]
This is fixed in 4.2.2. Pls update to the latest sdk.
Also, Pls post logs if you face it again

**Comment by moldy530** [comment]
Hey y'all, I'm seeing this same issue consistently when using Web3auth core and any of the `connectTo` methods. Can it be related or should I open a separate issue? I'm on a version>4.2.2 (I think 4.5, but stepped away from my pc right now)

**Comment by chusla** [comment]
hello i'm seeing this one as well, anyone from web3auth able to provide info on fixes?

![IMG_1660](https://user-images.githubusercontent.com/90009543/228951333-df474f43-444d-4818-8d39-72228945a67b.jpeg)
