### ISSUE TITLE
OpenLogin "disconnects" when refreshing the page on mobile browser

### ISSUE THREAD

**Issue by sergeyeremeev** [Web3Auth/Web3Auth#129]
When we use the OpenLogin adapter on our website after a successful login we get redirected to the next page. When in desktop mode everything works correctly, the connectedAdapterName is shown as 'openlogin' and trying to log the `web3Auth.provider` in our code prints out `Proxy {}` in the console.
<img width="1582" alt="Screenshot 2022-04-06 at 16 47 06" src="https://user-images.githubusercontent.com/4911237/161990541-3f702afc-b058-43c1-8b2d-51a6837701ed.png">

If we don't change anything, but simply toggle the responsive mode in google chrome and select iPhone XR as the device, upon refreshing the page we can see that the `connectedAdapterName` becomes `null` and `web3Auth.provider` also prints `null` to the browser console. This happens every single time and if we switch back to the desktop mode (without going through the login process, just switch to desktop and refresh) everything start working again, so it seems like the mobile browser is the issue.
<img width="1602" alt="Screenshot 2022-04-06 at 16 46 50" src="https://user-images.githubusercontent.com/4911237/161990558-34c0bd9f-7db0-46ba-8045-1c7f6e2300ec.png">

**Comment by chaitanyapotti** [comment]
Fixed in 0.8.2.
Thanks for reporting
