### ISSUE TITLE
Can't use method send With Smart Contracts Web3

### ISSUE THREAD

**Issue by pengjankul11** [Web3Auth/Web3Auth#141]
Hello,

I use web3Auth Authentication and config custom chain can get wallet address.
then i use web3.eth.Contract can get method call but not working method send show error 
<img width="720" alt="image" src="https://user-images.githubusercontent.com/103740751/163556271-7e209612-d9ff-453f-8ebb-2569eb3144f9.png">

<img width="570" alt="image" src="https://user-images.githubusercontent.com/103740751/163556655-c66da12c-50d2-43e6-9c72-463943e317f2.png">

What should I do this issue?

**Comment by chaitanyapotti** [comment]
This is fixed now
