### ISSUE TITLE
Restrict social logins

### ISSUE THREAD

**Issue by cardioprint** [Web3Auth/Web3Auth#148]
Hi guys! I'm struggling to do pretty basic thing - **allow only few social media for log in** and hide other ones in modal window.
I didn't found any recipe either in documentation nor articles on it.
So I'm modifying **react-app** example with latest @web3auth packages (0.9.3). [Here](https://github.com/Web3Auth/Web3Auth/blob/master/examples/react-app/src/services/web3auth.tsx#L107) all 14 _loginMethods_ are set for adapter OpenLogin, and this cannot be avoided. 
Adding code like this doesn't affect, as well as passing similar config to _initModal_:
```
          web3AuthInstance.loginModal.addSocialLogins(EVM_ADAPTERS.OPENLOGIN, {
            google: {
              name: "google",
              showOnModal: true,
              showOnDesktop: true,
              showOnMobile: true,
            },
            facebook: {
              name: "facebook",
              showOnModal: true,
              showOnDesktop: false,
              showOnMobile: true,
              mainOption: true,
              description: "facebook social login",
            },
          }, ['google', 'facebook'])
```
The reason (according to my debug) is wrong functioning of lodash.deepmerge, it doesn't override existing _loginMethods_. It happens in @web3auth/ui/src/components/Modal.tsx:62.

Any ideas on how to implement this must-be-simple thing or pointing, what I'm doing wrong, will be quite helpful

**Comment by himanshuchawla009** [comment]
here is the example in docs for your requirement:

https://docs.web3auth.io/api-reference/web/plugnplay#example-4

feel free to reopen issue if it doesn't help.

**Comment by cardioprint** [comment]
Thanks a lot, it helped! 
One should set `showOnModal: false` for every unwanted social media. 
There is also Typescript issue with `WALLET_ADAPTERS` in this example but it can be suppressed
