### ISSUE TITLE
Specified gasPrice Issue

### ISSUE THREAD

**Issue by Damin-Lee** [Web3Auth/Web3Auth#149]
If you connect metamask in openlogin, it works normally with the same settings, but if you use torus wallet, this error appears.

chunk-vendors.92e40d68.js:32 Uncaught (in promise) Error: Invalid transaction params: specified gasPrice but also included maxFeePerGas, these cannot be mixed

The chain setting proceeded as follows.
Network Name: Klaytn Baobab
New RPC URL: https://api.baobab.klaytn.net:8651
Block Explorer URL: https://baobab.scope.klaytn.com/
Chain ID: 1001 (0x3e9)
![photo_2022-04-27 14 03 30](https://user-images.githubusercontent.com/84518996/165444365-71e53e74-2068-4903-b190-9cd281f12876.jpeg)

**Comment by chaitanyapotti** [comment]
This is fixed in 1.0.0
