### ISSUE TITLE
`LOGIN_PROVIDER` not exported by @web3auth/openlogin-adapter error on building the app ( Vite+React+Typescript)

### ISSUE THREAD

**Issue by 0xharsha** [Web3Auth/Web3Auth#1573]
### **Describe the bug**
Build folder not getting generated on doing `yarn build`. (Using Vite+React+Typescript)

### **Screenshots**

<img width="1427" alt="Screenshot 2023-08-07 at 6 35 32 PM" src="https://github.com/Web3Auth/web3auth-web/assets/16958403/560a6d94-f273-4035-83ab-869bf4546665">

- Device: Macbook pro
- OS:  iOS

**Comment by chaitanyapotti** [comment]
This should be fixed in v7
