### ISSUE TITLE
Torus wallet network with TorusWalletConnectorPlugin has an unexpect performance.

### ISSUE THREAD

**Issue by refiny** [Web3Auth/Web3Auth#163]
Hello, Web3auth, there is a question about torus wallet network.

when I add TorusWalletConnectorPlugin, the torus wallet network is shown as https://goerli.infura.io/v3/776218ac4734478c90191dde8cae483c, I want to shown as default "Goerli Test Network", so what should I do for this purpose.

```javascript
const ethChainConfig: Partial<CustomChainConfig> & Pick<CustomChainConfig, "chainNamespace"> = {
  chainNamespace: CHAIN_NAMESPACES.EIP155,
  chainId: "0x5",
  ticker: "ETH",
  tickerName: "Ethereum",
};
```

![image](https://user-images.githubusercontent.com/15261334/167330324-59578b94-a382-4c7f-ba99-4821ec45bbef.png)

**Comment by tainguyentt** [comment]
Hi @refiny so it's about UI/UX and not a performance issue, right? We should display a concise name instead of a long URL

**Comment by refiny** [comment]
for a sign message, 'https://goerli.infura.io/v3/776218ac4734478c90191dde8cae483c' will got a blank page, but after switch to 'Goerli Test Network' manually will got a normal sign page.

![image](https://user-images.githubusercontent.com/15261334/167340420-a3c155a6-abde-427b-a49d-4c1980de11f8.png)
![image](https://user-images.githubusercontent.com/15261334/167340481-6b02f7e1-0e55-4d42-aba6-530ca3c0fe00.png)

**Comment by himanshuchawla009** [comment]
@refiny can you confirm version of torus wallet plugin that you are using?

**Comment by refiny** [comment]
"@web3auth/torus-wallet-connector-plugin": "^0.10.0",
