### ISSUE TITLE
"Activity" is not match in popup window and wallet management window.

### ISSUE THREAD

**Issue by refiny** [Web3Auth/Web3Auth#174]
Hi, guys, during the usage of torus wallet, I found that the popup window showed the latest activity, but after I click 'Open Wallet', swith to 'Activity' tab, it is empty, does that correct?

![image](https://user-images.githubusercontent.com/15261334/168040829-b371e01d-b189-4675-b7b7-c0e5f3a79f39.png)

**Comment by himanshuchawla009** [comment]
fixed in latest release
