### ISSUE TITLE
Wrong Re-Hydration of user info when using email as login method

### ISSUE THREAD

**Issue by cardosofelipe** [Web3Auth/Web3Auth#177]
**When**: After a successful login, using OpenLogin adapter, on a page refresh

**What happens**:  the userInfo object (  obtained by using  web3Auth.getUserInfo() ) contains typeOfLogin "google" with any email. The same field value was "jwt" right  after the first login.

**What is  expected**: that the userInfo info object is consistent at every web3Auth re-hydration, in this case I alway expect the field  typeOfLogin, to be  "jwt" (the same  value I got at  the first login)

**Additional data**:

- aggregateVerifier: "tkey-auth0-email-passwordless-lrc"
- verifier: "torus"
- browser info: {"browser":{"name":"Chrome","version":"100.0.4896.75"},"os":{"name":"Linux"},"platform":{"type":"desktop"},"engine":{"name":"Blink"}}

**Comment by himanshuchawla009** [comment]
it is fixed now, plz update to latest version of web3auth. Feel free to reopen if the issue still persist for you.
