### ISSUE TITLE
Torus Wallet with error "We're sorry but app doesn't work properly without javascript enabled. Please enable it to continue."

### ISSUE THREAD

**Issue by refiny** [Web3Auth/Web3Auth#187]
### **Describe the bug**

I my site, sometimes when I want to pay with torus wallet, but got a block page.

### **To Reproduce**

1, Write code to Send transaction:
```javascript
     await this.provider.request({
        method: 'eth_sendTransaction',
        params: [{
          from: _from,
          to,
          value: _value,
          data: _data,
          gas: Web3.utils.numberToHex('25000')
        }]
      })
```
2, click 'Send Transaction'
3, Page redirect success, but without any information.
4, from console page, see the error: We're sorry but app doesn't work properly without javascript enabled. Please enable it to continue.

### **Expected behavior**

Transaction page display.

### **Screenshots**

![image](https://user-images.githubusercontent.com/15261334/168716985-18a3e6a5-d189-4639-9781-3b1a0a2dc18f.png)
![image](https://user-images.githubusercontent.com/15261334/168717518-69922ab7-721c-456a-9a1e-c993d620336e.png)

### **Device Info (please complete the following information):**

- Device: Desktop
- OS: Windows 11
- Browser: Chrome
- Version: 100.0.4896.75
- Web3Auth Version: 1.0.0-alpha.0

**Comment by refiny** [comment]
Hi, Web3Auth, here is another way to reproduce this issue,  @chaitanyapotti you may call Tai Nguyen TT to get his private github repository https://github.com/tainguyentt/web3auth-react.git , I have already pull my code into this repository before.

**Steps to reproduce the behavior:**
1, start up this react project, and open the url in chrome.
2, login with your email address, then press "F12" to open chrome DevTools.
3, click "Toggle device toolbar" to change into Mobile model
4, click "Sign Message", the popup windows does not display the expected result
5, you will found the error info in chrome DevTool

**Screenshots**
![image](https://user-images.githubusercontent.com/15261334/168747237-f5b6e6fb-ab08-4f2b-a8fb-e07af6559016.png)

**Comment by chaitanyapotti** [comment]
This is already fixed :)
