### ISSUE TITLE
Polygon Mumbai RPC error

### ISSUE THREAD

**Issue by svskaushik** [Web3Auth/Web3Auth#204]
Hi

Using Web3Auth (through Moralis) on Polygon's Mumbai testnet has recently been throwing the following errors:

`Error: Could not connect via Web3Auth, error in connecting to provider`  and

```
Access to fetch at 'https://rpc-mumbai.maticvigil.com/' from origin 'https://3fi.vercel.app' has been blocked by CORS policy
```

I believe this isn't a problem on Web3Auth's end, as this `https://rpc-mumbai.maticvigil.com` seems to be down for multiple people, but perhaps we could change endpoints or add fallback endpoints to circumvent the problem?

Functioning endpoints for Mumbai currently :
`https://matic-mumbai.chainstacklabs.com`
`https://matic-testnet-archive-rpc.bwarelabs.com`

Not sure if this is exclusive to the Moralis integration or if it applies to regular integrations as well. Couldn't find a way to manually set endpoints, at least not for the Moralis integration.

Thanks

**Comment by himanshuchawla009** [comment]
Hey, moralis sdk doesn't expose parameters to update the chain endpoint, but web3auth sdk does. You can report this issue in moralis github. May be they will be able to resolve it. Thanks.
