### ISSUE TITLE
Remove "https://" requirement for auth0 domain

### ISSUE THREAD

**Issue by yashovardhan** [Web3Auth/Web3Auth#228]
### **Describe the bug**

When you're providing `extraLoginOptions`, in the domain field, you need to add `https:` before your auth0 domain. By default auth0 doesn't provide https in their console which makes it confusing for a developer.

### **To Reproduce**

1. Create auth0 tenant and verifier and follow standard example for auth0
2. Remove "https://" from `domain` in `extraLoginOptions`
3. Attempt login

### **Expected behavior**

It should go to my auth0 domain and login .

### **Screenshots**

<img width="770" alt="Screenshot 2022-06-16 at 2 29 19 PM" src="https://user-images.githubusercontent.com/21066442/174033987-d1a3f696-8575-4e3a-9cb3-c4bbbf9f9177.png">

![Screenshot 2022-06-16 at 2 29 51 PM](https://user-images.githubusercontent.com/21066442/174034119-a606d4a0-26dc-4f01-8b40-c0e933f2ea5e.png)

**Comment by himanshuchawla009** [comment]
although we can't remove it, but now it will show a better error msg.
