### ISSUE TITLE
How to interact with smart contracts using OpenLogin email sign on provider

### ISSUE THREAD

**Issue by Amirjab21** [Web3Auth/Web3Auth#247]
### **Is your feature request related to a problem? Please describe.**

I would like to use the email sign on in a similar way to a metamask wallet e.g interact with smart contracts. When I grab the signer from the OpenLogin provider, it does not let me interact with smart contracts.

### **Describe the solution you'd like**

An example or a way of interacting with smart contracts using the openLogin Adapter

**Comment by robaggio** [comment]
I just used OpenLogin provider(with TorusWalletConnectorPlugin) to interact with smart contracts. The code is the same as with the metamask, the only difference is no popup menu for users to confirm, the code just confirms it by default.

**Comment by himanshuchawla009** [comment]
@Amirjab21 , plz refer to examples here https://web3auth.io/docs/connect-blockchain/ethereum#smart-contract

**Comment by himanshuchawla009** [comment]
@robaggio Web3Auth doesn't open any popup by default, you can your own tx confirmation screens or if you want to use pre built tx popups you can use torus-wallet-connector-plugin with web3auth.

**Comment by robaggio** [comment]
> @robaggio Web3Auth doesn't open any popup by default, you can your own tx confirmation screens or if you want to use pre built tx popups you can use torus-wallet-connector-plugin with web3auth.

thanks, we did use torus-wallet-connector-plugin, but no tx popups showed, is there any settings to open this feature?

**Comment by himanshuchawla009** [comment]
you will need to use the provider instance variable from torus-wallet-connector-plugin class,  currently you must be using web3auth.provider but try using plugin.provider.

Feel free to reopen issue if this doesn't helps.
