### ISSUE TITLE
On some user devices we see endless loading on a modal

### ISSUE THREAD

**Issue by ximxim** [Web3Auth/Web3Auth#25]
On some user devices, we see endless loading on a modal, If the same user tries using open login in incognito mode of chrome browser. Things work fine. So I am wondering it has something to do with stored information on the device.

**Comment by himanshuchawla009** [comment]
@ximxim , it seems to be happening on calling connect function when user is already connected. In upcoming release, modal will not open (and will return provider) if user is already connected but you might also want to show the logged-in screen to user if a user is already connected. You can do this by checking if web3auth.provider is available after calling web3auth.initModal function.

**Comment by ximxim** [comment]
Thanks @himanshuchawla009 It turned out to be a problem with how we were consuming the sdk. Firstly, we weren't logging the user out properly. We had to the logout method of the sdk to do that. Secondly, we weren't resuming connection by checking if the provider was already there and connection was already established. Closing this bug.
