### ISSUE TITLE
Error: "ReferenceError: document is not defined" for NextJS

### ISSUE THREAD

**Issue by PlayVRS** [Web3Auth/Web3Auth#267]
### **Describe the bug**

Going through "Using Web3Auth NextJS Quick Start Guide" to setup a demo project, failed with error: 
`ReferenceError: document is not defined`

### **To Reproduce**

Following steps in ["Using Web3Auth NextJS Quick Start Guide"](https://web3auth.io/docs/integration-builder?lang=next&chain=eth&customAuthentication=yes&whitelabel=yes&customLogin=no#step-0)

### **Expected behavior**

View the demo page

### **Screenshots**

<img width="994" alt="image" src="https://user-images.githubusercontent.com/99873887/179659473-b161450a-4a24-424b-9f8b-3285ee3bfb9d.png">

### **Device Info (please complete the following information):**

- Device: [MacBook Pro]
- OS: [Mac OS Monterey]
- Browser [chrome]
- Web3Auth Version [1.1.1]

**Comment by denny999222** [comment]
What was the solution?
