### ISSUE TITLE
Cannot create Discord Verifier - Invalid Client Id

### ISSUE THREAD

**Issue by sophieqgu** [Web3Auth/Web3Auth#296]
### **Describe the bug**

Create Verifier wizard shows Discord Client ID invalid when copy/pasted from Discord developer console.

### **To Reproduce**

1. Follow https://web3auth.io/docs/custom-authentication/social-providers/discord
2. Copy "Client ID" from the OAuth2 page
3. Paste into "Enter Discord Client ID" shows client ID invalid. Deleting one digit and the error disappears.

### **Screenshots**
***Client ID from Discord developer console***
![Screen Shot 2022-07-28 at 9 48 32 PM](https://user-images.githubusercontent.com/37032128/181666295-26041ac6-8e1d-4f39-8236-8e8b4e1214e5.png)
***Client ID deleting 1 digit***
![Screen Shot 2022-07-28 at 9 48 39 PM](https://user-images.githubusercontent.com/37032128/181666293-6b8f97e6-4ec8-4ad4-af7c-2d45f71103cf.png)

### **Device Info (please complete the following information):**

- Device: Mac
- OS: MacOS
- Browser: Chrome
- Web3Auth Version: 1.1.1

**Comment by himanshuchawla009** [comment]
@BboyStatix
