### ISSUE TITLE
No idToken being returned

### ISSUE THREAD

**Issue by YZhenY** [Web3Auth/Web3Auth#362]
### Discussed in https://github.com/orgs/Web3Auth/discussions/361

<div type='discussions-op-text'>

<sup>Originally posted by **briankostar** August  3, 2022</sup>
Trying to login with Google -- after logging in, and doing web3auth.getUserInfo(), there is no tokenId. 
This is a problem as it as we cant verify the user on the backend without the tokenId. 

Issue is only with 1 particular google account after setting up 2FA. Other accounts are still ok. 

Clearing cookies, localstorage, and logging in from incognito show same issue.

<img width="1669" alt="Screen Shot 2022-08-02 at 3 14 45 PM" src="https://user-images.githubusercontent.com/4313671/182455688-b90918d2-b2a7-40d4-aa59-5d668e934389.png">

</div>

**Comment by himanshuchawla009** [comment]
we have fixed this issue, feel free to reopen if you still face this.
