### ISSUE TITLE
Can we add a public RPC endpoint as the default web3auth rpc endpoint?

### ISSUE THREAD

**Issue by yashovardhan** [Web3Auth/Web3Auth#389]
### **Is your feature request related to a problem? Please describe.**

After logging in multiple times in our demo apps, the rpc error shows - limit exceeded infura error. 

### **Describe the solution you'd like**

Currently we're using an internal infura RPC endpoint as the default rpcTarget when user doesn't provide anything from their side. Can we change to some public RPC endpoint so that this error can be by passed? There might be some rare cases where public RPC endpoints might be down, but the majority of times this can be better solution than using a rate limited infura endpoint.

### **Describe alternatives you've considered**

I checked around with multiple public rpc endpoints and private infura endpoints as well, I think this solution might work.

**Comment by himanshuchawla009** [comment]
```I checked around with multiple public rpc endpoints and private infura endpoints as well, I think this solution might work.```. Can you share non rate limited public endpoints?

**Comment by yashovardhan** [comment]
ankr endpoints have never stopped for me particularly. They also say that 1M daily requests are supported as I see: https://www.ankr.com/protocol/
