### ISSUE TITLE
Bad access token with Facebook (custom authentication)

### ISSUE THREAD

**Issue by NicoBeskar** [Web3Auth/Web3Auth#458]
I'm having trouble connecting the credentials I get from Facebook (Custom Authentication), with my Firebase Authentication service.

My code is the following:

```
const authCredential = FacebookAuthProvider.credential(userInfo.oAuthAccessToken);

this.auth.signInWithCredential(authCredential)
```

The error I get is:

Firebase: Bad access token: {"code":190,"subcode":466,"message":"Error validating access token: The session was invalidated explicitly using an API call."} (auth/invalid-credential).

Doing the same process with Google I was able to authenticate without problems, but with Facebook I get that the token is invalid.

- Device: Macbook Pro
- OS: macOS Monterrey 12.1
- Browser: Chrome
- Version: 104.0.5112.101
- Web3Auth Version: 1.1.4

**Comment by himanshuchawla009** [comment]
Hi, It is not related to Web3Auth sdk, plz create issue on firebase repo.
