### ISSUE TITLE
Getting "TypeError: _this.showExternalWallets is not a function" Error

### ISSUE THREAD

**Issue by leelakrishnan** [Web3Auth/Web3Auth#46]
Steps to recreate:
1. Create a Next js app. 
2. Create a Component to hold all Web3Auth related actions.
import {useRouter} from "next/router";
import { Web3Auth } from "@web3auth/web3auth";
import { ADAPTER_EVENTS, CHAIN_NAMESPACES } from "@web3auth/base";
import { LOGIN_MODAL_EVENTS } from "@web3auth/ui";
import React, { useEffect, useState } from "react";

import Button from '@mui/material/Button';
import Image from "next/image";

function Login() {
    const [user, setUser] = useState(null);
    const [web3auth, setWeb3auth] = useState(null);
    const [loaded, setLoaded] = useState(false);
    const [subscribed, setSubscribed] = useState(false);
    useEffect(() => {
        console.log("useEffect");

        const subscribeAuthEvents = (web3auth) => {
            console.log("subscribeAuthEvents ", subscribed);

            if (subscribed) {
                return;
            }
            web3auth.on(ADAPTER_EVENTS.CONNECTED, (data) => {
                debugger;
                console.log("Yeah!, you are successfully logged in", data);
                setUser(data);
            });

            web3auth.on(ADAPTER_EVENTS.CONNECTING, () => {
                debugger;
                console.log("connecting");
            });

            web3auth.on(ADAPTER_EVENTS.DISCONNECTED, () => {
                debugger;
                console.log("disconnected");
                setUser(null);
            });

            web3auth.on(ADAPTER_EVENTS.ERRORED, (error) => {
                debugger;
                console.log("some error or user have cancelled login request", error);
            });

            web3auth.on(LOGIN_MODAL_EVENTS.MODAL_VISIBILITY, (isVisible) => {
                debugger;
                console.log("modal visibility", isVisible);
            });

            setSubscribed(true);
        };

        const polygonMumbaiConfig = {
            chainNamespace: CHAIN_NAMESPACES.EIP155,
            rpcTarget: "your rpc target",
            blockExplorer: "https://mumbai-explorer.matic.today",
            chainId: "0x13881",
            displayName: "Polygon Mumbai Testnet",
            ticker: "matic",
            tickerName: "matic",
        };

        const web3auth = new Web3Auth({
            chainConfig: polygonMumbaiConfig,
            clientId: "your client id",
        });

        setWeb3auth(web3auth);

        // ⭐️ initialize modal on page mount.
        const initializeModal = async () => {
            console.log("initializeModal");
            subscribeAuthEvents(web3auth);
            await web3auth.initModal();
            setLoaded(true);
        };
        initializeModal();
    }, [subscribed]);

    const login = async () => {
        debugger;
        if (!web3auth) return;
        const provider = await web3auth.connect();
        // TODO: add this provider to web3/ethers
        debugger;
    };
    const logout = async () => {
        if (!web3auth) return;
        await web3auth.logout();
    };
    const getUserInfo = async () => {
        debugger;
        if (!web3auth) return;
        const userInfo = await web3auth.getUserInfo();
        console.log(userInfo);
    };

    const renderUnauthenticated = () => {
        return (
            <div>
                <Button variant="contained" onClick={login}>
                    LOGIN
                </Button>
            </div>
        );
    };

    const renderAuthenticated = () => {
        return (
            <div className="App">
                <Button variant="contained" onClick={logout}>
                    LOG OUT
                </Button>
                <Button variant="contained" onClick={getUserInfo}>
                </Button>
            </div>
        );
    };
    return loaded && user ? renderAuthenticated() : renderUnauthenticated();
}
export default Login;
3. Create a Home component added the login component as dynamic component
import React, { useEffect } from "react";
import { Box, Button } from "@mui/material";
import { useRouter } from "next/router";
import Image from "next/image";
import dynamic from 'next/dynamic'

const DynamicComponentWithNoSSR = dynamic(
    () => import('../components/Login'),
    { ssr: false }
)

function Home() {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  const router = useRouter();

  return (
    <Box
      sx={{
        height: "85vh",
        opacity: 0.9,
        filter: "brightness(0.9)",
        position: "relative",
        top: 0,
        zIndex: 0,
        display: "flex",
        justifyContent: "center",
        alignContent: "center",
        alignItems: "center",
        bgcolor: "black",
        flexDirection: "column",
      }}
    >
      <Image
        src="/images/background.jpeg"
        objectFit="cover"
        layout="fill"
        priority="true"
      />

      <Button onClick={() => router.push("/dashboard")}>
        <Image
          src="/images/logo.png"
          width="100%"
          height="100%"
          priority="true"
        />
      </Button>
      <DynamicComponentWithNoSSR />
    </Box>
  );
}

export default Home;
4. When we run the project and click on login button getting error:
![image](https://user-images.githubusercontent.com/2261933/152686500-b760c584-5c40-46db-925b-dd8df26eaac5.png)

**Comment by himanshuchawla009** [comment]
can u also attach errors from your browser console.

**Comment by himanshuchawla009** [comment]
it seems to be happening when not being able to connect with the rpc url.

**Comment by leelakrishnan** [comment]
Uncaught (in promise) TypeError: _this.showExternalWallets is not a function
    at LoginModal.eval [as toggleModal] (ui.esm.js?7a1a:361:1)
    at Web3Auth.connect (web3auth.esm.js?e12b:361:1)
    at _callee$ (Login.js?650c:87:41)
    at tryCatch (runtime.js?ecd4:45:16)
    at Generator.invoke [as _invoke] (runtime.js?ecd4:274:1)
    at Generator.prototype.<computed> [as next] (runtime.js?ecd4:97:1)
    at asyncGeneratorStep (Login.js?650c:8:31)
    at _next (Login.js?650c:8:31)
    at eval (Login.js?650c:8:31)
    at new Promise (<anonymous>)
    at eval (Login.js?650c:8:31)
    at login (Login.js?650c:84:16)
    at HTMLUnknownElement.callCallback (react-dom.development.js?ac89:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?ac89:3994:1)
    at invokeGuardedCallback (react-dom.development.js?ac89:4056:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js?ac89:4070:1)
    at executeDispatch (react-dom.development.js?ac89:8243:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js?ac89:8275:1)
    at processDispatchQueue (react-dom.development.js?ac89:8288:1)
    at dispatchEventsForPlugins (react-dom.development.js?ac89:8299:1)
    at eval (react-dom.development.js?ac89:8508:1)
    at batchedEventUpdates$1 (react-dom.development.js?ac89:22396:1)
    at batchedEventUpdates (react-dom.development.js?ac89:3745:1)
    at dispatchEventForPluginEventSystem (react-dom.development.js?ac89:8507:1)
    at attemptToDispatchEvent (react-dom.development.js?ac89:6005:1)
    at dispatchEvent (react-dom.development.js?ac89:5924:1)
    at unstable_runWithPriority (scheduler.development.js?bcd2:468:1)
    at runWithPriority$1 (react-dom.development.js?ac89:11276:1)
    at discreteUpdates$1 (react-dom.development.js?ac89:22413:1)
    at discreteUpdates (react-dom.development.js?ac89:3756:1)
    at dispatchDiscreteEvent (react-dom.development.js?ac89:5889:1)

**Comment by himanshuchawla009** [comment]
also please attach your network calls, i want to see if rpc url is connecting or not.

**Comment by leelakrishnan** [comment]
![image](https://user-images.githubusercontent.com/2261933/152693748-632be559-1cfc-4f5a-a54f-bbac64be8a95.png)

**Comment by himanshuchawla009** [comment]
another reason can be that you are calling connect function before initModal is finished.  Make sure to call connect function only after finishing initModal.

replace : ``` loaded && user ? renderAuthenticated() : renderUnauthenticated();```   with  ```loaded ? (user ? renderAuthenticated() : renderUnauthenticated()): <h1>Loading....</h1>;```

**Comment by leelakrishnan** [comment]
ok thanks
