### ISSUE TITLE
SendTransaction not working

### ISSUE THREAD

**Issue by himanshuchawla009** [Web3Auth/Web3Auth#469]
### Discussed in https://github.com/orgs/Web3Auth/discussions/461

<div type='discussions-op-text'>

<sup>Originally posted by **KetulCodiste** August 23, 2022</sup>
I have implemented the React + web3Auth demo from the web3Auth documentation. All the functions are working fine except the sendTransaction function. It gives me the following error: 

Error: Internal JSON-RPC error.
    at getEthJsonRpcError (errors.ts:188:1)
    at Object.internal (errors.ts:52:1)
    at provider.sendAsync (INetworkController.ts:125:1)
    at async provider.request (INetworkController.ts:149:1)

I also tried to implement one more function which uses .send() method. So, .call() method is working correctly but .send() method is giving this error. 
I have not made any changes in the demo, just copy/pasted the code in my local machine. </div>

**Comment by himanshuchawla009** [comment]
resolved gas price issues in latest release

**Comment by gaiverrr** [comment]
@himanshuchawla009 I have same issue, can you pls provide more details about how this bug can be resolved?

**Comment by arpita-enstead** [comment]
@himanshuchawla009 can you plz provide a solution to this error?
