### ISSUE TITLE
wagmi connector

### ISSUE THREAD

**Issue by billtlee** [Web3Auth/Web3Auth#483]
We are using moralis to build our app.  The version 1 of the sdk has connector for web3auth.  However, on their v2 they are using wagmi and there is currently no connector for web3auth.  So, we can't upgrade to their v2 sdk.  There is already a wagmi connector for magic link.  Seems magic link is your competitor, it might be worth while to release a wagmi connector.

**Comment by himanshuchawla009** [comment]
Hey @billtlee , our wagmi connector is in testing , we will release it soon. I will post you here once after releasing it.

**Comment by himanshuchawla009** [comment]
We just published web3auth connector for wagmi here: https://www.npmjs.com/package/@web3auth/web3auth-wagmi-connector
