### ISSUE TITLE
update docs and examples to use existing "enums" instead of hardcoded strings

### ISSUE THREAD

**Issue by gotjoshua** [Web3Auth/Web3Auth#52]
It seems that internally base and core are using constants from here:
https://github.com/Web3Auth/Web3Auth/blob/master/packages/base/src/adapter/IAdapter.ts#L51

I feel that it would be better form to use these constants (or even better, actual ts enums) in the example code and the docs instead of the hardcoded strings:

https://github.com/Web3Auth/Web3Auth/blob/118c0b8d405f2bf8fb1794a8b3221c8a0bf6d42c/examples/getting-started/eth/index.html#L51-L54

could look like:
```js
web3auth.on(ADAPTER_STATUS.CONNECTED, (data) => {
                console.log("Yeah!, you are successfully logged in", data);
});
```

**Comment by himanshuchawla009** [comment]
we can't do it only for umd builds coz or extra script import, for rest of the examples and docs we have updated these.
