### ISSUE TITLE
All examples demos are fail to run

### ISSUE THREAD

**Issue by koakh** [Web3Auth/Web3Auth#69]
all examples **next-app, react-app, vue-app** are fail when run

ex react-app

```shell
cd Web3Auth/examples/react-app
$ npm i
$ npm run start
```

as a test to play with web3auth I only fix the minor issue in react-app, to fix replace 

```typescript
  return loaded ? user ? renderAuthenticated() : renderUnauthenticated() : <h1>Loading....</h1>;
```

```typescript
  return !isLoading
    ? user ? renderAuthenticated() : renderUnauthenticated()
    : <h1>Loading....</h1>;
```

thanks for this awesome project

**Comment by himanshuchawla009** [comment]
Hi @koakh , can u try using the example again, we are actively improving our examples and have updated the react one recently.  If you still face any issue, please share the error logs from console for debugging.

Thanks for reporting issue.

**Comment by chaitanyapotti** [comment]
We've updated all examples to fix this issue
