### ISSUE TITLE
Error: Invalid network, net_version is: '97'

### ISSUE THREAD

**Issue by snigdha920** [Web3Auth/Web3Auth#83]
### Issue
I'm trying to use the Web3Auth (web) to integrate sign-in in my application. I've connected to the Binance Testnet Chain in the config, but while trying to login with the Magic link and the social logins, I get the following error: 
<img width="2032" alt="image" src="https://user-images.githubusercontent.com/62167899/157641419-b2b5ee52-1297-44de-9926-5dee14796ade.png">

### Repo for reproduction

Here's a repo I created which reproduces the issues along with how to run the repo and details on the issue I found during my investigation: https://github.com/snigdha920/web3-auth

**Comment by himanshuchawla009** [comment]
the network endpoint ( 'https://binance-testnet-node-197c.settlemint.com/bpaas-c2d7ed1bf72AB0b5Db82D5c405f9C677355d5914`) that you are using is returning network version in a weird format "'97'" as shown in image below. Try using some other endpoint which returns version in correct format as number 97 or as a string "97".

<img width="441" alt="Screenshot 2022-03-10 at 4 17 48 PM" src="https://user-images.githubusercontent.com/14052374/157646461-cd9eb6fc-f65e-479a-a4ec-784992bb2617.png">

**Comment by snigdha920** [comment]
Yep, we fixed it on our end! Thank you for your help :)

**Comment by snigdha920** [comment]
Btw, created a PR fixing an issue I faced while using the next example repo here: https://github.com/Web3Auth/Web3Auth/pull/84
