### ISSUE TITLE
react examples failed to run

### ISSUE THREAD

**Issue by asandoval2313** [Web3Auth/Web3Auth#87]
Getting this error when trying to run the react-app and custom-ui-react-app examples 

Error: NormalModuleFactory.resolve (NormalModuleFactory) is no longer a waterfall hook, but a bailing hook instead. Do not return the passed object, but modify it instead. Returning false will ignore the request and results in no module created. Returning a Module object will result in this module used as result.

**Comment by himanshuchawla009** [comment]
@asandoval2313 can you add some steps that you are using to run the example which might help us to reproduce this issue.

**Comment by asandoval2313** [comment]
@himanshuchawla009 I cloned the repo, changed directories into react-app (within the examples folder), ran npm install, then npm start. This then produced the error mentioned in my original post.

**Comment by himanshuchawla009** [comment]
we have updated example, can you try once again @asandoval2313

**Comment by himanshuchawla009** [comment]
closing it as failed to reproduce.
