### ISSUE TITLE
openlogin adapter disconnected on hard refresh

### ISSUE THREAD

**Issue by goosecoid** [Web3Auth/Web3Auth#90]
Hi,

When logging in with Metamask, hard refreshing doesn't disconnect. Whilst using social login or email link (openlogin), when refreshing the adapter disconnects: i.e. `web3auth.connectedAdapterName: null` and `web3auth.status: ready`, instead of `openlogin` and `connected` respectively.

Thanks in advance.

**Comment by himanshuchawla009** [comment]
@goosecoid  plz provider browser and os details.

**Comment by goosecoid** [comment]
Tried on windows, linux and macOs. Tried it on firefox and chrome.

**Comment by goosecoid** [comment]
Just some extra context. I also saw that after logging in no Cookie is set, which doesn't save the login session. Hence the loss of the session when refreshing. Is this normal? Is there a parameter we should pass to fix this? Thanks in advance.

**Comment by YosephKS** [comment]
Yeahh I found this problem as well. Somehow so weird that some of the production apps shown are able to persist their sessions. Is a custom logic to manage session in this case required? @himanshuchawla009

**Comment by chaitanyapotti** [comment]
Fixed in 0.8.2.
Thanks for reporting
