### ISSUE TITLE
"View more options" is not needed when there are less than 4 options under 'CONNECT WITH'.

### ISSUE THREAD

**Issue by VinaySagarN** [Web3Auth/Web3Auth#92]
UI issue in modal under https://demo-app.web3auth.io

View more options is not needed when there are less than 4 options under 'CONNECT WITH'.
https://demo-app.web3auth.io

![image](https://user-images.githubusercontent.com/90750562/159404684-685235b2-689f-4b45-abc1-29e51383f68e.png)

**Comment by himanshuchawla009** [comment]
already fixed here #91 , waiting for @chaitanyapotti to merge it

**Comment by chaitanyapotti** [comment]
Fixed
